
- name: print ansible_distribution
  debug:
    var: ansible_distribution


# gather os specific cats:
- include_tasks: "{{item}}"
  with_first_found:
    - "{{ansible_distribution}}-{{ansible_distribution_major_version}}.yml"
    - "{{ansible_distribution}}.yml"
  tags: os_specific
